services:
  magic-services-cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: magic-services-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
      REAL_IP_HEADER: Cf-Connecting-Ip
    networks:
      - app
    depends_on:
      - magic-keycloak
      - magic-btcpayserver

  magic-keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: magic-keycloak
    restart: unless-stopped
    command: start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app

  magic-btcpayserver:
    restart: unless-stopped
    container_name: magic-btcpayserver
    image: btcpayserver/btcpayserver:2.3.5
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=magic-btcpay-postgres;Port=5432;Application Name=btcpayserver;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=magic-btcpay-postgres;Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BTCEXPLORERURL: http://magic-nbxplorer:32838
      BTCPAY_CHEATMODE: true
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_VERBOSE: true
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_DOCKERDEPLOYMENT: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - btcpay_datadir:/datadir
      - nbxplorer_datadir:/root/.nbxplorer
      - btcpay_pluginsdir:/root/.btcpayserver/Plugins
    ports:
      - 49392:49392
    networks:
      - app

  magic-bitcoind:
    restart: unless-stopped
    container_name: magic-bitcoind
    image: btcpayserver/bitcoin:30.2
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        port=39388
        whitelist=0.0.0.0/0
        rpcallowip=0.0.0.0/0
        rpcuser=magic
        rpcpassword=magic
        fallbackfee=0.00001
    ports:
      - 43782:43782
      - 39388:39388
    volumes:
      - bitcoin_datadir:/home/bitcoin/.bitcoin
    networks:
      - app

  magic-nbxplorer:
    restart: unless-stopped
    container_name: magic-nbxplorer
    image: nicolasdorier/nbxplorer:2.6.1
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_NOAUTH: true
      NBXPLORER_EXPOSERPC: true
      NBXPLORER_CHAINS: btc
      NBXPLORER_BTCRPCURL: http://magic-bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: magic-bitcoind:39388
      NBXPLORER_BTCRPCUSER: magic
      NBXPLORER_BTCRPCPASSWORD: magic
      NBXPLORER_POSTGRES: User ID=postgres;Host=magic-btcpay-postgres;Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
    volumes:
      - nbxplorer_datadir:/datadir
      - bitcoin_datadir:/root/.bitcoin
    networks:
      - app

  magic-btcpay-postgres:
    restart: unless-stopped
    container_name: magic-btcpay-postgres
    shm_size: 256mb
    image: btcpayserver/postgres:18.1
    command: ['-c', 'random_page_cost=1.0', '-c', 'shared_preload_libraries=pg_stat_statements']
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - btcpay_postgres_datadir:/var/lib/postgresql
    networks:
      - app

volumes:
  btcpay_datadir:
  btcpay_pluginsdir:
  bitcoin_datadir:
  nbxplorer_datadir:
  btcpay_postgres_datadir:
